# Generated by Django 3.0.3 on 2021-12-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=64, verbose_name='工作名称')),
                ('jobSalary', models.CharField(max_length=64)),
                ('jobLimitExperience', models.CharField(max_length=64)),
                ('jobLimitStudy', models.CharField(max_length=64)),
                ('jobArea', models.CharField(max_length=64)),
                ('companyName', models.CharField(max_length=64)),
                ('financialStatus', models.CharField(max_length=64)),
                ('scale', models.CharField(max_length=64)),
                ('companyLogo', models.CharField(max_length=256)),
                ('bonus', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '职业大类',
                'verbose_name_plural': '职业大类',
                'db_table': 'bigJob',
            },
        ),
    ]
