# Generated by Django 3.1.7 on 2022-01-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigjob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigjob',
            name='jobCat',
            field=models.IntegerField(default=11, verbose_name='catid'),
            preserve_default=False,
        ),
    ]
