# Generated by Django 3.1.7 on 2022-01-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigjob', '0003_auto_20220102_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobCat', models.IntegerField(verbose_name='catid')),
                ('jobName', models.CharField(max_length=64, verbose_name='工作名称')),
                ('jobSalary', models.CharField(max_length=64)),
                ('jobLimitExperience', models.CharField(max_length=64)),
                ('jobLimitStudy', models.CharField(max_length=64)),
                ('jobArea', models.CharField(max_length=64)),
                ('companyName', models.CharField(max_length=64)),
                ('financialStatus', models.CharField(max_length=64)),
                ('scale', models.CharField(max_length=64)),
                ('companyLogo', models.CharField(max_length=256)),
                ('bonus', models.CharField(max_length=64)),
                ('holland1', models.CharField(max_length=1)),
                ('holland2', models.CharField(max_length=1)),
                ('holland3', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': '具体岗位',
                'verbose_name_plural': '具体岗位',
                'db_table': 'job',
            },
        ),
    ]
