# Generated by Django 3.1.7 on 2022-01-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigjob', '0004_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bigjob',
            old_name='companyLogo',
            new_name='bigJobImg',
        ),
        migrations.RemoveField(
            model_name='bigjob',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='bigjob',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='bigjob',
            name='financialStatus',
        ),
        migrations.RemoveField(
            model_name='bigjob',
            name='jobArea',
        ),
        migrations.RemoveField(
            model_name='bigjob',
            name='jobLimitExperience',
        ),
        migrations.RemoveField(
            model_name='bigjob',
            name='jobLimitStudy',
        ),
        migrations.RemoveField(
            model_name='bigjob',
            name='jobSalary',
        ),
        migrations.RemoveField(
            model_name='bigjob',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='job',
            name='holland1',
        ),
        migrations.RemoveField(
            model_name='job',
            name='holland2',
        ),
        migrations.RemoveField(
            model_name='job',
            name='holland3',
        ),
        migrations.RemoveField(
            model_name='job',
            name='jobCat',
        ),
        migrations.AddField(
            model_name='bigjob',
            name='jobDesc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bigjob',
            name='jobWork',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bigjob',
            name='subject1',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bigjob',
            name='subject2',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='jobIndustry',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='jobSubName',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
