# Generated by Django 3.1.7 on 2022-01-03 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigjob', '0005_auto_20220103_0432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BigJob',
        ),
    ]
