# Generated by Django 3.1.7 on 2022-01-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigjob', '0006_delete_bigjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobCat', models.IntegerField(verbose_name='catid')),
                ('jobName', models.CharField(max_length=64, verbose_name='工作名称')),
                ('jobDesc', models.TextField()),
                ('jobWork', models.TextField()),
                ('bigJobImg', models.CharField(max_length=256)),
                ('holland1', models.CharField(max_length=1)),
                ('holland2', models.CharField(max_length=1)),
                ('holland3', models.CharField(max_length=1)),
                ('subject1', models.CharField(max_length=64)),
                ('subject2', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '职业大类',
                'verbose_name_plural': '职业大类',
                'db_table': 'bigJob',
            },
        ),
    ]
