# Generated by Django 3.1.7 on 2022-01-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigjob', '0007_bigjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jid',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='lid',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
