# Generated by Django 3.1.7 on 2022-01-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigjob', '0008_auto_20220103_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobDescription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
