# Generated by Django 3.1.7 on 2022-01-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigjob', '0009_job_jobdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigjob',
            name='bigJobImg',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bigjob',
            name='holland1',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='bigjob',
            name='holland2',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='bigjob',
            name='holland3',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='bigjob',
            name='jobDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bigjob',
            name='jobWork',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bigjob',
            name='subject1',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bigjob',
            name='subject2',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='bonus',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='companyLogo',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='companyName',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='financialStatus',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobArea',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobIndustry',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobLimitExperience',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobLimitStudy',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobSalary',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobSubName',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='scale',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
