openapi: "3.0.2"
info:
  title: MyJob Platform API Documentation
  version: "1.0"
  description: "This is the API documentation of MyJob Platform website."
  contact:
    email: "clearbamboo@outlook.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: https://localhost:8080/api
    description: "Local test server"
tags:
  - name: bigJob
    description: "The information about 'bigJob'"
  - name: job
    description: "Specific job information"
  - name: user
    description: "User control"
  - name: "personality"
    description: "Personality calculation"
  - name: "graph"
    description: "Some data to draw graph"
  - name: "test"
    description: "Test API"
paths:
  /test:
    get:
      tags:
        - "test"
      summary: "Test if the API is usable"
      description: ""
      
      responses:
        "200":
          description: OK
  /user/users:
    get:
      tags:
        - "user"
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
