openapi: "3.0.2"
info:
  title: MyJob Platform API Documentation
  version: "1.0.0"
  description: "This is the API documentation of MyJob Platform website."
  contact:
    email: "clearbamboo@outlook.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: https://localhost:8080/api
    description: "Local test server"

components:
  schemas:
    jobCat:
      type: string
      description: Code string of bigjob
      example: "2005003008"

tags:
  - name: bigJob
    description: "The information about 'bigJob'"
  - name: job
    description: "Specific job information"
  - name: user
    description: "User control"
  - name: "graph"
    description: "Some data to draw graph"
  - name: "test"
    description: "Test API"
paths:
  /test:
    get:
      tags:
        - "test"
      summary: "Test if the API is usable"
      description: ""
      responses:
        "200":
          description: OK
  /user/users:
    get:
      tags:
        - "user"
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /bigjob/jobs:
    get:
      tags:
        - "bigJob"
      summary: Get Job by holland code
      parameters:
        - in: query
          name: key1
          required: true
          description: First Holland code
          schema:
            type: string
            example: "I"
        - in: query
          name: key2
          required: true
          description: Second Holland code
          schema:
            type: string
            example: "S"
        - in: query
          name: key3
          required: true
          description: Third Holland code
          schema:
            type: string
            example: "R"
      responses:
        "200":
          description: Successfully get big job information
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobCat:
                    $ref: "#/components/schemas/jobCat"
                  bigJobImg:
                    type: string
                    description: Job cartoon image from 104 website
                    example: "https:\/\/static.104.com.tw\/gtnew\/img\/character\/bigRole\/2005003008.png"
                  jobName:
                    type: string
                    description: Name of Job
                    example: "醫藥業務代表"
                  jobDesc:
                    type: string
                    description: Simple description of Job
                    example: "我會把藥賣出去，推廣客戶需要的醫療產品！"
                  jobWorks:
                    type: string
                    description: Specific description of job work
                    example: "拜訪固定或非固定地區醫院、診所、藥局客戶，以開發或維護客戶關係。\n銷售及推廣公司產品，例如醫療研究用儀器或醫藥耗材等。\n教育及示範產品使用方式。\n協助客戶使用產品。\n提供新客戶相關之行銷或經營輔導。\n宣導與執行公司的理念予店家。"
                  subject1:
                    type: string
                    description: First level subject
                    example: "social"
                  subject2:
                    type: string
                    description: Second level subject
                    example: "biology"
  /bigjob/tags:
    get:
      description: "Get inffered tags of big job"
      tags:
        - "bigJob"
      parameters:
        - in: query
          name: jobCat
          required: true
          schema:
            $ref: "#/components/schemas/jobCat"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  certification:
                    type: array
                    items:
                      type: object
                      properties:
                        desc:
                          type: string
                          example: 普考护士执照
                        count:
                          type: integer
                          example: 500
                  skill:
                    type: array
                    items:
                      type: object
                      properties:
                        desc:
                          type: string
                          example: 业务或道路开发
                        count:
                          type: integer
                          example: 500
                  tool:
                    type: array
                    items:
                      type: object
                      properties:
                        desc:
                          type: string
                          example: Outlook
                        count:
                          type: integer
                          example: 500
  /bigjob/personality:
    get:
      description: Get five dimantional personality result, which reflect positive(乐观正面), cooperation(团队合作)、cautious(谨慎坚毅)、dominate(积极主导)、innovative(创新开放)
      tags:
        - "bigJob"
      parameters:
        - in: query
          name: jobCat
          required: true
          schema:
            $ref: "#/components/schemas/jobCat"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: number
                example: [3.82, 0.86, 3.81, 4.18, 4.45]
  /bigjob/wage:
    get:
      description: Get wage of bigjob
      tags:
        - "bigJob"
      parameters:
        - in: query
          name: jobCat
          required: true
          schema:
            $ref: "#/components/schemas/jobCat"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  avgWage:
                    type: number
                    example: 45333.12
  /bigjob/major:
    get:
      description: get the major of this bigjob
      tags:
        - "bigJob"
      parameters:
        - in: query
          name: jobCat
          required: true
          schema:
            $ref: "#/components/schemas/jobCat"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    majorName:
                      type: string
                      example: 护理学系
                    count:
                      type: integer
                      example: 500
  /bigjob/ageSex:
    get:
      description: get age and sex distribution
      tags:
        - "bigJob"
      parameters:
        - in: query
          name: jobCat
          required: true
          schema:
            $ref: "#/components/schemas/jobCat"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "17": { "male": 0.2, "female": 0.05 },
                    "18": { "male": 0.3, "female": 0.01 },
                  }
  /bigjob/task:
    get:
      description: ""
      tags:
        - "bigJob"
      parameters:
        - in: query
          name: jobCat
          required: true
          schema:
            $ref: "#/components/schemas/jobCat"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    example: 负责公司医疗器材产品推广
                  missions:
                    type: array
                    items:
                      type: string
                      example: 协助客户使用产品
  /user/login:
    get:
      description: ""
      tags:
        - "user"
      parameters: []
      responses:
        "200":
          description: OK
  /user/register:
    get:
      description: ""
      tags:
        - "user"
      parameters: []
      responses:
        "200":
          description: OK
  /job/detail:
    get:
      description: "get specific job details"
      tags:
        - "job"
      parameters: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobName:
                    type: string
                    example: 医药代表
                  jobSalary:
                    type: string
                    example: 15-20k·13薪
                  jobLimitExperience:
                    type: string
                    example: 经验不限
                  jobLimitStudy:
                    type: string
                    example: 大专
                  jobArea:
                    type: string
                    example: 上海·浦东新区·张江
                  companyName:
                    type: string
                    example: 阿斯利康
                  financialStatus:
                    type: string
                    example: 已上市
                  scale:
                    type: string
                    example: 10000人以上
                  companyLogo:
                    type: string
                    example: companyLogo
                  bonus:
                    type: string
                    example: 带薪年假
  /user/logout:
    get:
      description: ""
      tags:
        - "user"
      parameters: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  loginStatus:
                    type: boolean
                    example: true
  /bigjob/hollandCode:
    post:
      description: "holland code calculation"
      tags:
        - "bigjob"
      requestBody:
        description: true of false answer of hollan test
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                hollandAnswer:
                  type: array
                  example: [0, 1, 1, 1, 1, 0, 1, 1, 0, 1]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  key1:
                    type: string
                    example: "I"
                  key2:
                    type: string
                    example: "I"
                  key3:
                    type: string
                    example: "I"
